# Generated by Django 2.2.5 on 2019-10-22 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('bias', models.FloatField(default=0)),
                ('variance', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'db_table': 'accounts',
                'swappable': 'AUTH_USER_MODEL',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.AutoField(db_column='area_id', primary_key=True, serialize=False)),
                ('area_name', models.CharField(db_column='area_name', max_length=30, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'areas',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(db_column='genre_id', primary_key=True, serialize=False)),
                ('genre_name', models.CharField(db_column='genre name', max_length=30, unique=True)),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_column='updated_at', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('situation_id', models.AutoField(db_column='situation_id', primary_key=True, serialize=False)),
                ('situation_name', models.CharField(db_column='situation name', max_length=30, unique=True)),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_column='updated_at', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'situations',
            },
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('spot_id', models.AutoField(db_column='spot_id', primary_key=True, serialize=False)),
                ('spot_name', models.CharField(db_column='spot_name', max_length=30, unique=True)),
                ('evaluated_score', models.FloatField(db_column='evaluated_score', default=3.0)),
                ('latitude', models.FloatField(blank=True, db_column='latitude', null=True)),
                ('longitude', models.FloatField(blank=True, db_column='longitude', null=True)),
                ('link', models.URLField(blank=True, db_column='link', null=True)),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_column='updated_at', default=django.utils.timezone.now)),
                ('area', models.ForeignKey(db_column='area', on_delete=django.db.models.deletion.CASCADE, to='rest.Area')),
                ('genre', models.ForeignKey(db_column='genre', on_delete=django.db.models.deletion.CASCADE, to='rest.Genre')),
            ],
            options={
                'db_table': 'spots',
            },
        ),
        migrations.CreateModel(
            name='Kuchikomi',
            fields=[
                ('kuchikomi_id', models.AutoField(db_column='kuchikomi_id', primary_key=True, serialize=False)),
                ('price', models.FloatField(db_column='price')),
                ('score', models.FloatField(db_column='score')),
                ('comment', models.TextField(blank=True, db_column='comment', max_length=1000, null=True)),
                ('deviation', models.FloatField(blank=True, db_column='deviation', null=True)),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_column='updated_at', default=django.utils.timezone.now)),
                ('account', models.ForeignKey(db_column='account', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('situation', models.ForeignKey(db_column='situation', on_delete=django.db.models.deletion.CASCADE, to='rest.Situation')),
                ('spot', models.ForeignKey(db_column='spot', on_delete=django.db.models.deletion.CASCADE, to='rest.Spot')),
            ],
        ),
    ]
