# Generated by Django 2.2.5 on 2019-10-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bias',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='variance',
            field=models.FloatField(default=0),
        ),
    ]
