# Generated by Django 2.2.5 on 2019-10-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_account_evals'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='inyou',
            field=models.FloatField(db_column='inyou', default=50),
        ),
        migrations.AddField(
            model_name='account',
            name='oshare',
            field=models.FloatField(db_column='oshare', default=50),
        ),
        migrations.AddField(
            model_name='account',
            name='setsuyaku',
            field=models.FloatField(db_column='setsuyaku', default=50),
        ),
        migrations.AddField(
            model_name='account',
            name='shokuji',
            field=models.FloatField(db_column='shokuji', default=50),
        ),
    ]
