# Generated by Django 2.2.5 on 2019-10-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20191026_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='setsuyaku',
        ),
    ]
