# Generated by Django 2.2.5 on 2019-10-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_remove_account_setsuyaku'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='setsuyaku',
            field=models.FloatField(db_column='setsuyaku', default=50),
        ),
    ]
